name: Release

on:
  push:
    tags:
      - 'v*'
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
jobs:
  release:

    runs-on: ubuntu-latest
    timeout-minutes: 6

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x      
    - name: Get build version
      run: |        
        $ref = "${env:GITHUB_REF}"
        $version = $ref.Substring($ref.LastIndexOf("/") + 2)
        echo "version=${version}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
    - name: Clean
      run: 
        dotnet clean
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run:  |
        dotnet build --no-restore -p:Version=$version --configuration Release /p:PublishReadyToRun=true /p:TieredCompilation=false /p:TieredCompilationQuickJit=false
    - name: Publish Nuget
      run:  |
        dotnet nuget push **/*.nupkg --api-key ${{ secrets.GITHUBWRITEPACKAGES }} --source ${{ secrets.GITHUBNUGETURL }}